CyberPay/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from CyberPay.core import views as core_views
from CyberPay.wallet import views as wallet_views

urlpatterns = [
    url(r'^$', core_views.index, name='index'),
    url(r'^wallet/$', wallet_views.home, name='home'),
    url(r'^login/$', auth_views.login, {'template_name': 'core/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^wallet/', include('CyberPay.wallet.urls')),
    url(r'^admin/', admin.site.urls),
]

CyberPay/wallet/urls.py
from django.conf.urls import url

from . import views

app_name = 'wallet'
urlpatterns = [
    url(r'^transactions/', views.transactions, name='transactions'),
    url(r'^deposit/', views.deposit, name='deposit'),
    url(r'^withdraw/', views.withdraw, name='withdraw'),
]

CyberPay/core/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

CyberPay/wallet/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    balance = models.DecimalField(max_digits=20, decimal_places=6, default=0)
    updated = models.DateTimeField(default=timezone.now)

    @receiver(post_save, sender=User)
    def create_user_account(sender, instance, created, **kwargs):
        if created:
            Account.objects.create(user=instance)

    def __str__(self):
        name = self.user.get_full_name()
        return name if name else self.user.username


class Transaction(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    balance_before = models.DecimalField(decimal_places=6, max_digits=20)
    balance_after = models.DecimalField(decimal_places=6, max_digits=20)
    note = models.CharField(max_length=255, null=True)

    @property
    def amount(self):
        return self.balance_after - self.balance_before

    def __str__(self):
        return '{} at {:%Y-%m-%d %H:%M:%S %z} (before=${:,.2f}, after=${:,.2f})'\
            .format(self.account, self.created, self.balance_before, self.balance_after)

CyberPay/wallet/forms.py
from django import forms


class MyForm(forms.Form):
    amount = forms.DecimalField(min_value=0.01, max_value=10 ** 12, decimal_places=2)
    note = forms.CharField(max_length=255, required=False)

CyberPay/core/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render


def index(request):
    if request.user.is_anonymous:
        return redirect('login')
    else:
        return redirect('home')


def signup(request):
    if request.user.is_authenticated:
        return redirect('home')
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'core/signup.html', {'form': form})

CyberPay/wallet/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import transaction
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone

from CyberPay.wallet.forms import MyForm
from CyberPay.wallet.models import Transaction, Account


@login_required
def home(request):
    user = request.user
    latest_transactions = Transaction.objects.filter(account__user_id=user.id).order_by('-created')[:5]
    return render(request, 'wallet/base.html', {'transactions': latest_transactions})


@login_required
def transactions(request):
    user = request.user
    transaction_list = Transaction.objects.filter(account__user_id=user.id).order_by('-created')
    paginator = Paginator(transaction_list, 10)

    page = request.GET.get('page')
    try:
        result = paginator.page(page)
    except PageNotAnInteger:
        result = paginator.page(1)
    except EmptyPage:
        result = paginator.page(paginator.num_pages)
    return render(request, 'wallet/transactions.html', {'transactions': result})


@login_required
def deposit(request):
    if request.method == "POST":
        form = MyForm(request.POST)
        if form.is_valid():
            with transaction.atomic():
                create_transaction(Account.objects.select_for_update().get(user_id=request.user.id),
                                   form.cleaned_data['amount'],
                                   form.cleaned_data['note'])
            return HttpResponseRedirect(reverse('wallet:transactions'))
    else:
        form = MyForm()
    return render(request, 'wallet/deposit_form.html', {'form': form})


@login_required
def withdraw(request):
    if request.method == "POST":
        form = MyForm(request.POST)
        if form.is_valid():
            amount = form.cleaned_data['amount']
            with transaction.atomic():
                account = Account.objects.select_for_update().get(user_id=request.user.id)
                if amount <= account.balance:
                    create_transaction(account, amount * -1, form.cleaned_data['note'])
                    return HttpResponseRedirect(reverse('wallet:transactions'))
                else:
                    form.add_error('amount',
                                   "Cannot withdraw more than the current balance of ${:,.2f}".format(account.balance))
    else:
        form = MyForm()
    return render(request, 'wallet/withdraw_form.html', {'form': form})


def create_transaction(account, amount, note):
    old_balance = account.balance
    account.balance = old_balance + amount
    now = timezone.now()
    account.updated = now
    account.save()
    return Transaction.objects.create(account=account, created=now, balance_before=old_balance,
                                      balance_after=account.balance, note=note)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}CyberPay{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'core.css' %}">
</head>
<body>
<header>
    <h1>CyberPay</h1>
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">logout</a>
    {% else %}
        <a href="{% url 'login' %}">login</a> / <a href="{% url 'signup' %}">signup</a>
    {% endif %}
    <hr>
</header>
<main class="main row">
    {% block content %}
    {% endblock %}
</main>
</body>
</html>

templates/core/login.html
{% extends 'base.html' %}

{% block content %}
    <h2>Log in to My Site</h2>
    {% if form.errors %}
        <p style="color: red">Your username and password didn't match. Please try again.</p>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}<br>
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            {% if field.help_text %}
                <p>
                    <small style="color: grey">{{ field.help_text }}</small>
                </p>
            {% endif %}
            </p>
        {% endfor %}
        <button type="submit">Log in</button>
        <a href="{% url 'signup' %}">New to My Site? Sign up</a>
    </form>
{% endblock %}

templates/core/signup.html
{% extends 'base.html' %}

{% block content %}
    <h2>Sign up</h2>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: red">{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <button type="submit">Sign up</button>
    </form>
{% endblock %}

templates/wallet/base.html
{% extends 'base.html' %}
{% load core_filters %}

{% block content %}
    <div class="sidebar col-2">
        <h2><a href="{% url 'home' %}">{{ user }}</a></h2>
        <h5>{{ user.account.balance|currency:2 }}</h5>
        <ul>
            <li><a href="{% url 'wallet:transactions' %}">View Transactions</a></li>
            <li><a href="{% url 'wallet:deposit' %}">Deposit</a></li>
            <li><a href="{% url 'wallet:withdraw' %}">Withdraw</a></li>
        </ul>
    </div>
    <div class="container col-10">
        <h2>{% block heading %}Recent transactions{% endblock %}</h2>
        <br/>
        {% block wallet_content %}
            {% include 'wallet/transaction_table.html' %}
        {% endblock %}
    </div>
{% endblock %}

templates/wallet/deposit_form.html
{% extends 'wallet/base.html' %}

{% block heading %}
    Deposit to the wallet
{% endblock %}

{% block wallet_content %}
    <form action="{% url 'wallet:deposit' %}" method="post" class="col-8">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <fieldset>
            <div class="form-group row required {% if form.amount.errors %}has-danger{% endif %}">
                <label for="{{ form.amount.id_for_label }}" class="col-form-label col-2">Amount ($)</label>
                <div class="col-10">
                    <input class="form-control" type="number" step="0.01" placeholder="0.00" value="{{ form.amount.value }}"
                           id="{{ form.amount.id_for_label }}" name="{{ form.amount.name }}">
                    <span class="form-control-feedback">{{ form.amount.errors }}</span>
                </div>
            </div>
            <div class="form-group row">
                <label for="{{ form.note.id_for_label }}" class="col-form-label col-2">Note</label>
                <div class="col-10">
                    <textarea class="form-control" placeholder="Note to the transaction"
                              id="{{ form.note.id_for_label }}" name="{{ form.note.name }}">{% if form.note.value %}
                        {{ form.note.value }}{% endif %}</textarea>
                    <span class="form-control-feedback">{{ form.note.errors }}</span>
                </div>
            </div>
        </fieldset>
        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="OK">
        </div>
    </form>
{% endblock %}

templates/wallet/transaction_table.html
{% load core_filters %}
{% load tz %}

<table class="table table-sm table-striped">
    <thead>
    <tr>
        <th>Time</th>
        <th>Note</th>
        <th>Amount</th>
        <th>Balance Before</th>
        <th>Balance After</th>
    </tr>
    </thead>
    <tbody>
    {% localtime on %}
        {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.created|localtime|date:"Y-m-d H:i:s" }}</td>
                <td>{{ transaction.note|default_if_none:"" }}</td>
                <td>{{ transaction.amount|currency:2 }}</td>
                <td>{{ transaction.balance_before|currency:2 }}</td>
                <td>{{ transaction.balance_after|currency:2 }}</td>
            </tr>
        {% endfor %}
    {% endlocaltime %}
    </tbody>
</table>

templates/wallet/transactions.html
{% extends 'wallet/base.html' %}
{% load humanize %}

{% block heading %}
    All transactions
{% endblock %}

{% block wallet_content %}
    {% include 'wallet/transaction_table.html' %}

    <div class="pagination">
    <span class="step-links">
        {% if transactions.has_previous %}
            <a href="?page={{ transactions.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ transactions.number }} of {{ transactions.paginator.num_pages }}
        </span>

        {% if transactions.has_next %}
            <a href="?page={{ transactions.next_page_number }}">Next</a>
        {% endif %}
    </span>
    </div>
{% endblock %}

templates/wallet/withdraw_form.html
{% extends 'wallet/base.html' %}

{% block heading %}
    Withdraw from the wallet
{% endblock %}

{% block wallet_content %}
    <form action="{% url 'wallet:withdraw' %}" method="post" class="col-8">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <fieldset>
            <div class="form-group row required {% if form.amount.errors %}has-danger{% endif %}">
                <label for="{{ form.amount.id_for_label }}" class="col-form-label col-2">Amount ($)</label>
                <div class="col-10">
                    <input class="form-control" type="number" step="0.01" placeholder="0.00"
                           value="{{ form.amount.value }}"
                           id="{{ form.amount.id_for_label }}" name="{{ form.amount.name }}">
                    <span class="form-control-feedback">{{ form.amount.errors }}</span>
                </div>
            </div>
            <div class="form-group row">
                <label for="{{ form.note.id_for_label }}" class="col-form-label col-2">Note</label>
                <div class="col-10">
                    <textarea class="form-control" placeholder="Note to the transaction"
                              id="{{ form.note.id_for_label }}" name="{{ form.note.name }}">{% if form.note.value %}
                        {{ form.note.value }}{% endif %}</textarea>
                    <span class="form-control-feedback">{{ form.note.errors }}</span>
                </div>
            </div>
        </fieldset>
        <div class="form-actions">
            <input type="submit" class="btn btn-primary" value="OK">
        </div>
    </form>
{% endblock %}